version: "3.7"
services:
  db:
    image: postgres:14-alpine3.18
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
  
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    external_links:
      - db
    depends_on:
      - db
volumes:
  db: